export const mediaItems = [
  { type: "image", src: "/gallery/_0000_PHOTO14.jpg" },
  { type: "gif", src: "/gallery/Vídeo02_1.gif" },
  { type: "image", src: "/gallery/_0001_PHOTO13.jpg" },
  { type: "image", src: "/gallery/_0002_PHOTO12.jpg" },
  { type: "image", src: "/gallery/_0003_PHOTO11.jpg" },
  { type: "gif", src: "/gallery/Vídeo05_1.gif" },
  { type: "image", src: "/gallery/_0004_PHOTO10.jpg" },
  { type: "image", src: "/gallery/_0005_PHOTO09.jpg" },
  { type: "image", src: "/gallery/test.jpg" },
  { type: "gif", src: "/gallery/Vídeo07_1.gif" },
  { type: "image", src: "/gallery/_0007_PHOTO07.jpg" },
  { type: "image", src: "/gallery/_0008_PHOTO06.jpg" },
  { type: "image", src: "/gallery/_0009_PHOTO05.jpg" },
  { type: "image", src: "/gallery/_0010_PHOTO04.jpg" },
  { type: "gif", src: "/gallery/Vídeo03_1.gif" },
  { type: "image", src: "/gallery/_0011_PHOTO03.jpg" },
  { type: "image", src: "/gallery/_0012_PHOTO02.jpg" },
  { type: "image", src: "/gallery/_0013_PHOTO01.jpg" },
  { type: "gif", src: "/gallery/Video01_1.gif" },
];
